# See: 
#   https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#configuration
#   https://github.com/marketplace/actions/action-for-semantic-release

branches: ["master", "main"]
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"