# This workflow will build a Java project with Gradle then perform an automated release
# For more information see:
#  https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#  https://github.com/marketplace/actions/action-for-semantic-release

name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Fix for docker.sock issue
        run: |
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-directory
          path: build
      - uses: codecov/codecov-action@v3
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true
  release:
    needs: build
    uses: lsd-consulting/shared-workflows/.github/workflows/release.yml@main
    with:
      java-version: '17'
    secrets: inherit
