name: Merge dependabot PR
on:
  pull_request_target:
    branches:
      - main
      - master
jobs:
  pr-merge:
    uses: lsd-consulting/shared-workflows/.github/workflows/dependabot-merge.yml@main
    secrets: inherit