name: Nightly Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # run at 2 AM UTC
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha
        run: |
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
      - name: Build with Gradle
        run: ./gradlew build
