name: Nightly Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # run at 2 AM UTC
jobs:
  build:
    uses: lsd-consulting/shared-workflows/.github/workflows/build.yml@main
    with:
      java-version: '17'
      operating-system: ubuntu-22.04
